# Generated by Django 5.1.7 on 2025-07-11 23:05

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Addres'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, validators=[usuarios.models.validar_fecha_nacimiento], verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=9, unique=True, validators=[usuarios.models.validar_pasaporte], verbose_name='Passport'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Statement of Account'),
        ),
    ]
