# Generated by Django 5.1.7 on 2025-04-04 05:23

import django.contrib.auth.models
import django.db.models.deletion
import django_countries.fields
import estudiantes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.CharField(default='Estudiante', max_length=20)),
                ('nacionalidad', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('usuarios.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inscripcion', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('pasaporte', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/pasaporte/', validators=[estudiantes.models.validar_archivo])),
                ('documento_identidad', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/identidad/', validators=[estudiantes.models.validar_archivo])),
                ('antecedentes_penales', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/antecedentes/', validators=[estudiantes.models.validar_archivo])),
                ('seguro_medico', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/seguro/', validators=[estudiantes.models.validar_archivo])),
                ('carta_inscripcion', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/carta_inscripcion/', validators=[estudiantes.models.validar_archivo])),
                ('recibo_pago', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/pago/', validators=[estudiantes.models.validar_archivo])),
                ('diploma_traducido', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/diploma/', validators=[estudiantes.models.validar_archivo])),
                ('transcripcion_traducida', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/transcripcion/', validators=[estudiantes.models.validar_archivo])),
                ('carta_intencion', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/carta_intencion/', validators=[estudiantes.models.validar_archivo])),
                ('resumen_financiero', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/resumen_financiero/', validators=[estudiantes.models.validar_archivo])),
                ('extracto_bancario', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/extracto_bancario/', validators=[estudiantes.models.validar_archivo])),
                ('mensaje_rechazo', models.TextField(blank=True, help_text='Motivo del rechazo de la inscripción.', null=True, verbose_name='Mensaje de Rechazo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado_inscripcion', models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='estudiantes.estudiantes')),
            ],
        ),
    ]
