# Generated by Django 5.1.7 on 2025-05-30 18:26

import django.contrib.auth.models
import django.db.models.deletion
import django_countries.fields
import estudiantes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rol', models.CharField(default='Estudiante', max_length=20)),
                ('nacionalidad', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('usuarios.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inscripcion', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('passport_copy', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/pasaporte_copy/', validators=[estudiantes.models.validar_archivo], verbose_name='Passport Copy (Data Page and all signed/stamped/visa pages)')),
                ('previous_visa_refusal_letters', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/visa_refusal/', validators=[estudiantes.models.validar_archivo], verbose_name='Previous Visa Refusal Letters (if applicable)')),
                ('national_id_copy', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/national_id/', validators=[estudiantes.models.validar_archivo], verbose_name='National ID Copy')),
                ('biometric_photos', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/photos/', validators=[estudiantes.models.validar_archivo], verbose_name='2 Biometric Photos (35x45 size)')),
                ('police_clearance_certificates', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/police_clearance/', validators=[estudiantes.models.validar_archivo], verbose_name='Police Clearance Certificates')),
                ('travel_health_insurance', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/health_insurance/', validators=[estudiantes.models.validar_archivo], verbose_name='Travel Health Insurance')),
                ('enrollment_letter', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/enrollment_letter/', validators=[estudiantes.models.validar_archivo], verbose_name='Enrollment Letter from SEDA')),
                ('booking_letter', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/booking_letter/', validators=[estudiantes.models.validar_archivo], verbose_name='Booking Letter from SEDA')),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/payment_receipt/', validators=[estudiantes.models.validar_archivo], verbose_name='Payment Receipt from SEDA')),
                ('diploma_translated', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/diploma_translated/', validators=[estudiantes.models.validar_archivo], verbose_name='Recent Diploma Translated into English')),
                ('transcript_translated', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/transcript_translated/', validators=[estudiantes.models.validar_archivo], verbose_name='Recent Transcript Translated into English')),
                ('student_letter', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/student_letter/', validators=[estudiantes.models.validar_archivo], verbose_name='Student Letter from College (if applicable)')),
                ('payslips_last_3_months', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/payslips/', validators=[estudiantes.models.validar_archivo], verbose_name='Payslips for Last 3 Months (if employed)')),
                ('Applicants_translated_work_history', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/Applicants_translated_work_history/', validators=[estudiantes.models.validar_archivo], verbose_name="Applicant's Employment History")),
                ('supportive_certificate', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/supportive_certificate/', validators=[estudiantes.models.validar_archivo], verbose_name='Supportive Certificate or Reasons to Study English Abroad')),
                ('intention_letter', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/intention_letter/', validators=[estudiantes.models.validar_archivo], verbose_name='Intention Letter')),
                ('reason_for_return', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/reason_for_return/', validators=[estudiantes.models.validar_archivo], verbose_name='Reason for Return')),
                ('financial_summary_form', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/financial_summary/', validators=[estudiantes.models.validar_archivo], verbose_name='Financial Summary Form')),
                ('sponsorship_letter', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/sponsorship_letter/', validators=[estudiantes.models.validar_archivo], verbose_name='Sponsorship Letter (if applicable)')),
                ('visa_application_form', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/visa_application/', validators=[estudiantes.models.validar_archivo], verbose_name='Online Visa Application Form and Its Summary')),
                ('bank_statement', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/bank_statement/', validators=[estudiantes.models.validar_archivo], verbose_name='6 Months Bank Statement (Proof of 10,000 Euros)')),
                ('mensaje_rechazo', models.TextField(blank=True, help_text='Motivo del rechazo de la inscripción.', null=True, verbose_name='Mensaje de Rechazo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('estado_inscripcion', models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20)),
                ('necesita_patrocinio', models.BooleanField(default=False, verbose_name='Need sponsorship?')),
                ('id_patrocinador', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/id/', validators=[estudiantes.models.validar_archivo], verbose_name='ID o pasaporte del patrocinador')),
                ('carta_patrocinio', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/carta/', validators=[estudiantes.models.validar_archivo])),
                ('prueba_relacion', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/relacion/', validators=[estudiantes.models.validar_archivo])),
                ('estados_bancarios_patrocinador', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/estado_bancario/', validators=[estudiantes.models.validar_archivo], verbose_name='Estado bancario (6 meses)')),
                ('prueba_ingresos', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/ingresos/', validators=[estudiantes.models.validar_archivo], verbose_name='Prueba de ingresos')),
                ('detalles_empresa', models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/empresa/', validators=[estudiantes.models.validar_archivo], verbose_name='Documentos de empresa (si aplica)')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='estudiantes.estudiantes')),
            ],
            options={
                'permissions': [('view_documentos_pendientes', 'Puede ver documentos pendientes'), ('approve_documentos', 'Puede aprobar documentos'), ('reject_documentos', 'Puede rechazar documentos')],
            },
        ),
    ]
