# Generated by Django 5.1.7 on 2025-04-06 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentosestudiante',
            options={'permissions': [('view_documentos_pendientes', 'Puede ver documentos pendientes'), ('approve_documentos', 'Puede aprobar documentos'), ('reject_documentos', 'Puede rechazar documentos')]},
        ),
    ]
