# Generated by Django 5.1.7 on 2025-07-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosestudiante',
            name='Applicants_translated_work_history_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='Applicants_translated_work_history_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='bank_statement_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='bank_statement_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='biometric_photos_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='biometric_photos_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='booking_letter_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='booking_letter_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='diploma_translated_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='diploma_translated_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='enrollment_letter_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='enrollment_letter_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='financial_summary_form_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='financial_summary_form_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='intention_letter_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='intention_letter_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='national_id_copy_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='national_id_copy_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='passport_copy_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='passport_copy_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='payment_receipt_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='payment_receipt_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='payslips_last_3_months_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='payslips_last_3_months_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='police_clearance_certificates_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='police_clearance_certificates_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='previous_visa_refusal_letters_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='previous_visa_refusal_letters_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='reason_for_return_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='reason_for_return_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='sponsorship_letter_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='sponsorship_letter_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='student_letter_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='student_letter_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='supportive_certificate_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='supportive_certificate_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='transcript_translated_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='transcript_translated_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='travel_health_insurance_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='travel_health_insurance_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='visa_application_form_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='visa_application_form_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
    ]
