# Generated by Django 5.1.7 on 2025-04-10 20:41

import django.db.models.deletion
import estudiantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alter_documentosestudiante_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosestudiante',
            name='necesita_patrocinio',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Patrocinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_patrocinador', models.CharField(max_length=255)),
                ('carta_patrocinio', models.FileField(upload_to='documentos_patrocinador/carta/', validators=[estudiantes.models.validar_archivo])),
                ('identificacion_patrocinador', models.FileField(upload_to='documentos_patrocinador/identificacion/', validators=[estudiantes.models.validar_archivo])),
                ('prueba_relacion', models.FileField(upload_to='documentos_patrocinador/relacion/', validators=[estudiantes.models.validar_archivo])),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patrocinador', to='estudiantes.estudiantes')),
            ],
        ),
    ]
