# Generated by Django 5.1.7 on 2025-07-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_documentosestudiante_applicants_translated_work_history_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosestudiante',
            name='carta_patrocinio_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='carta_patrocinio_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='detalles_empresa_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='detalles_empresa_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='estados_bancarios_patrocinador_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='estados_bancarios_patrocinador_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='id_patrocinador_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='id_patrocinador_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='prueba_ingresos_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='prueba_ingresos_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='prueba_relacion_estado',
            field=models.CharField(choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En Revisión', max_length=20),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='prueba_relacion_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Mensaje de Rechazo del Documento'),
        ),
    ]
