# Generated by Django 5.1.7 on 2025-07-11 23:05

import estudiantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_documentosestudiante_carta_patrocinio_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='visa_application_form',
        ),
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='visa_application_form_estado',
        ),
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='visa_application_form_mensaje',
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='Applicants_translated_work_history_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='Applicants_translated_work_history_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='bank_statement_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='bank_statement_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='biometric_photos_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='biometric_photos_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='booking_letter_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='booking_letter_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='carta_patrocinio_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='carta_patrocinio_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='detalles_empresa',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/empresa/', validators=[estudiantes.models.validar_archivo], verbose_name='Company documents (if applicable)'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='detalles_empresa_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='detalles_empresa_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='diploma_translated_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='diploma_translated_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='enrollment_letter_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='enrollment_letter_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='estado_inscripcion',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='estados_bancarios_patrocinador',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/estado_bancario/', validators=[estudiantes.models.validar_archivo], verbose_name='Bank statement (6 months)'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='estados_bancarios_patrocinador_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='estados_bancarios_patrocinador_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='financial_summary_form_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='financial_summary_form_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='id_patrocinador',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/id/', validators=[estudiantes.models.validar_archivo], verbose_name='Sponsor ID or passport'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='id_patrocinador_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='id_patrocinador_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='intention_letter_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='intention_letter_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='national_id_copy_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='national_id_copy_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='passport_copy_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='passport_copy_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='payment_receipt_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='payment_receipt_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='payslips_last_3_months_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='payslips_last_3_months_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='police_clearance_certificates_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='police_clearance_certificates_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='previous_visa_refusal_letters_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='previous_visa_refusal_letters_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='prueba_ingresos',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/ingresos/', validators=[estudiantes.models.validar_archivo], verbose_name='Proof of income'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='prueba_ingresos_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='prueba_ingresos_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='prueba_relacion_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='prueba_relacion_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='reason_for_return_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='reason_for_return_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='sponsorship_letter_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='sponsorship_letter_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='student_letter_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='student_letter_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='supportive_certificate_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='supportive_certificate_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='transcript_translated_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='transcript_translated_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='travel_health_insurance_estado',
            field=models.CharField(choices=[('En Revisión', 'Under Review'), ('Aprobado', 'Approved'), ('Rechazado', 'Rejected')], default='En Revisión', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentosestudiante',
            name='travel_health_insurance_mensaje',
            field=models.TextField(blank=True, null=True, verbose_name='Document Rejection Message'),
        ),
    ]
