# Generated by Django 5.1.7 on 2025-04-10 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0003_documentosestudiante_necesita_patrocinio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='necesita_patrocinio',
        ),
        migrations.DeleteModel(
            name='Patrocinador',
        ),
    ]
