# Generated by Django 5.1.7 on 2025-04-13 16:46

import estudiantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_remove_documentosestudiante_necesita_patrocinio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosestudiante',
            name='carta_patrocinio',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/carta/', validators=[estudiantes.models.validar_archivo]),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='detalles_empresa',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/empresa/', validators=[estudiantes.models.validar_archivo], verbose_name='Documentos de empresa (si aplica)'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='estados_bancarios_patrocinador',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/estado_bancario/', validators=[estudiantes.models.validar_archivo], verbose_name='Estado bancario (6 meses)'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='id_patrocinador',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/id/', validators=[estudiantes.models.validar_archivo], verbose_name='ID o pasaporte del patrocinador'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='necesita_patrocinio',
            field=models.BooleanField(default=False, verbose_name='Need sponsorship?'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='prueba_ingresos',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/ingresos/', validators=[estudiantes.models.validar_archivo], verbose_name='Prueba de ingresos'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='prueba_relacion',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/patrocinio/relacion/', validators=[estudiantes.models.validar_archivo]),
        ),
    ]
