# Generated by Django 5.1.7 on 2025-05-04 20:07

import estudiantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_documentosestudiante_carta_patrocinio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='antecedentes_penales',
        ),
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='carta_inscripcion',
        ),
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='carta_intencion',
        ),
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='diploma_traducido',
        ),
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='documento_identidad',
        ),
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='extracto_bancario',
        ),
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='pasaporte',
        ),
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='recibo_pago',
        ),
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='resumen_financiero',
        ),
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='seguro_medico',
        ),
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='transcripcion_traducida',
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='bank_statement',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/bank_statement/', validators=[estudiantes.models.validar_archivo], verbose_name='6 Months Bank Statement (Proof of 10,000 Euros)'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='biometric_photos',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/photos/', validators=[estudiantes.models.validar_archivo], verbose_name='2 Biometric Photos (35x45 size)'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='booking_letter',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/booking_letter/', validators=[estudiantes.models.validar_archivo], verbose_name='Booking Letter from SEDA'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='diploma_translated',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/diploma_translated/', validators=[estudiantes.models.validar_archivo], verbose_name='Recent Diploma Translated into English'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='employment_history',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/employment_history/', validators=[estudiantes.models.validar_archivo], verbose_name="Applicant's Employment History"),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='enrollment_letter',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/enrollment_letter/', validators=[estudiantes.models.validar_archivo], verbose_name='Enrollment Letter from SEDA'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='financial_summary_form',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/financial_summary/', validators=[estudiantes.models.validar_archivo], verbose_name='Financial Summary Form'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='intention_letter',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/intention_letter/', validators=[estudiantes.models.validar_archivo], verbose_name='Intention Letter'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='national_id_copy',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/national_id/', validators=[estudiantes.models.validar_archivo], verbose_name='National ID Copy'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='passport_copy',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/pasaporte_copy/', validators=[estudiantes.models.validar_archivo], verbose_name='Passport Copy (Data Page and all signed/stamped/visa pages)'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/payment_receipt/', validators=[estudiantes.models.validar_archivo], verbose_name='Payment Receipt from SEDA'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='payslips_last_3_months',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/payslips/', validators=[estudiantes.models.validar_archivo], verbose_name='Payslips for Last 3 Months (if employed)'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='police_clearance_certificates',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/police_clearance/', validators=[estudiantes.models.validar_archivo], verbose_name='Police Clearance Certificates'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='previous_visa_refusal_letters',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/visa_refusal/', validators=[estudiantes.models.validar_archivo], verbose_name='Previous Visa Refusal Letters (if applicable)'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='reason_for_return',
            field=models.TextField(blank=True, help_text='Education, job offer, social and economic reasons.', null=True, verbose_name='Reason for Return to Home Country'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='student_letter',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/student_letter/', validators=[estudiantes.models.validar_archivo], verbose_name='Student Letter from College (if applicable)'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='supportive_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/supportive_certificate/', validators=[estudiantes.models.validar_archivo], verbose_name='Supportive Certificate or Reasons to Study English Abroad'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='transcript_translated',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/transcript_translated/', validators=[estudiantes.models.validar_archivo], verbose_name='Recent Transcript Translated into English'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='travel_health_insurance',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/health_insurance/', validators=[estudiantes.models.validar_archivo], verbose_name='Travel Health Insurance'),
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='visa_application_form',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/visa_application/', validators=[estudiantes.models.validar_archivo], verbose_name='Online Visa Application Form and Its Summary'),
        ),
    ]
