# Generated by Django 5.1.7 on 2025-05-05 00:29

import estudiantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_remove_documentosestudiante_antecedentes_penales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentosestudiante',
            name='sponsorship_letter',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/sponsorship_letter/', validators=[estudiantes.models.validar_archivo], verbose_name='Sponsorship Letter (if applicable)'),
        ),
    ]
