# Generated by Django 5.1.7 on 2025-05-12 17:44

import estudiantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0007_documentosestudiante_sponsorship_letter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosestudiante',
            name='employment_history',
        ),
        migrations.AddField(
            model_name='documentosestudiante',
            name='Applicants_translated_work_history',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/Applicants_translated_work_history/', validators=[estudiantes.models.validar_archivo], verbose_name="Applicant's Employment History"),
        ),
    ]
