# Generated by Django 5.1.7 on 2025-05-12 19:28

import estudiantes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0008_remove_documentosestudiante_employment_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosestudiante',
            name='reason_for_return',
            field=models.FileField(blank=True, null=True, upload_to='documentos_estudiantes/reason_for_return/', validators=[estudiantes.models.validar_archivo], verbose_name='Reason for Return'),
        ),
    ]
